# Generated by Django 5.0.6 on 2024-05-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
