# Generated by Django 5.0.6 on 2024-05-24 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_instagrampost_image_url_instagramimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagrampost',
            old_name='comments',
            new_name='comments_count',
        ),
        migrations.CreateModel(
            name='InstagramComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sentiment', models.CharField(default='neutral', max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='analysis.instagrampost')),
            ],
        ),
    ]
